### ISSUE TITLE
Multi-Step-Form - there is a big mistake in your code

### ISSUE THREAD

**Issue by mbcodecamp1** [AustinShelby/Multi-Step-Form#1]
Hi Austin,
there is a big mistake in your code!
If I jump from the 3rd step again to the 1st step - then afterwards the value in the 2nd step is missing!
What is the reason for this?
Best regards
Markus

**Comment by AustinShelby** [comment]
I think it's because of the inputs getting unregistered and therefore losing their state due to being removed from the dom.

This code was mostly just for an example for the tutorial. In a real project I would take more care to avoid any bugs.
